export type themesI =
    | 'abcdef'
    | 'androidstudio'
    | 'atomone'
    | 'bespin'
    | 'darcula'
    | 'dracula'
    | 'duotoneDark'
    | 'duotoneLight'
    | 'eclipse'
    | 'githubDark'
    | 'githubLight'
    | 'okaidia'
    | 'sublime'
